name: crypto_snap
description: Simple crypto chart app
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  fl_chart: ^0.66.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  google_fonts: ^5.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
